steps:
  # Install dependencies and build the Next.js application
  - name: 'node:18-alpine'
    entrypoint: sh
    args:
      - '-c'
      - |
        corepack enable
        corepack prepare pnpm@latest --activate
        pnpm install --frozen-lockfile
        pnpm build

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/dom-repo/dom-website-v3',
      '--build-arg', 'FIREBASE_PRIVATE_KEY=${_FIREBASE_PRIVATE_KEY}',
      '--build-arg', 'FIREBASE_CLIENT_EMAIL=${_FIREBASE_CLIENT_EMAIL}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_API_KEY=${_NEXT_PUBLIC_FIREBASE_API_KEY}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_PROJECT_ID=${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${_NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_APP_ID=${_NEXT_PUBLIC_FIREBASE_APP_ID}',
      '--build-arg', 'NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${_NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}',
      '--build-arg', 'NEXT_PUBLIC_EMAILJS_SERVICE_ID=${_NEXT_PUBLIC_EMAILJS_SERVICE_ID}',
      '--build-arg', 'NEXT_PUBLIC_EMAILJS_PUBLIC_KEY=${_NEXT_PUBLIC_EMAILJS_PUBLIC_KEY}',
      '--build-arg', 'NEXT_PUBLIC_EMAILJS_ADMIN_TEMPLATE_ID=${_NEXT_PUBLIC_EMAILJS_ADMIN_TEMPLATE_ID}',
      '--build-arg', 'NEXT_PUBLIC_EMAILJS_USER_TEMPLATE_ID=${_NEXT_PUBLIC_EMAILJS_USER_TEMPLATE_ID}',
      '--build-arg', 'NEXT_PUBLIC_ADMIN_EMAIL=${_NEXT_PUBLIC_ADMIN_EMAIL}',
      '--build-arg', 'NEXT_PUBLIC_ORG_NAME=${_NEXT_PUBLIC_ORG_NAME}',
      '.'
    ]

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/dom-repo/dom-website-v3']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dom-website-v3'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/dom-repo/dom-website-v3'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/dom-repo/dom-website-v3'

substitutions:
  _FIREBASE_PRIVATE_KEY: ''
  _FIREBASE_CLIENT_EMAIL: ''
  _NEXT_PUBLIC_FIREBASE_API_KEY: ''
  _NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ''
  _NEXT_PUBLIC_FIREBASE_PROJECT_ID: ''
  _NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ''
  _NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ''
  _NEXT_PUBLIC_FIREBASE_APP_ID: ''
  _NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ''
  _NEXT_PUBLIC_EMAILJS_SERVICE_ID: ''
  _NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: ''
  _NEXT_PUBLIC_EMAILJS_ADMIN_TEMPLATE_ID: ''
  _NEXT_PUBLIC_EMAILJS_USER_TEMPLATE_ID: ''
  _NEXT_PUBLIC_ADMIN_EMAIL: ''
  _NEXT_PUBLIC_ORG_NAME: '' 